---
development: &development
  adapter: sqlite
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *development
  database: db/test.sqlite3

production:
  <<: *development
  adapter: psql
  database: db/production.sqlite3
