---
development: &development
  mimetypes:
    azw3: application/x-mobi8-ebook
    css: text/css
    epub: application/epub+zip
    gif: image/gif
    jpeg: image/jpeg
    js: text/javascript
    mobi: application/x-mobipocket-ebook
    mp3: audio/mpeg
    mp4: audio/mp4
    opf: application/x-dtbncx+xml
    otf: font/otf
    pdf: application/pdf
    pls: application/pls+xml
    png: image/png
    smil: application/smil+xml
    svg: image/svg+xml
    tff: font/tff
    woff2: font/woff2
    woff: font/woff
    xhtml: application/xhtml+xml
    xml: application/xml

test:
  <<: *development

production:
  <<: *development
